data<-read.csv("car_price.csv")
View(data)
hist(data$SalePrice)
boxplot(data$SalePrice)
scatter.smooth(data$SalePrice)
mean(data$SalePrice)
mode(data$SalePrice)
median(data$SalePrice)
summary(data$SalePrice)
IQR(data$SalePrice)
quantile(data$SalePrice,0.30)
range(data$SalePrice)
lf<- quantile(data$SalePrice)-1.5*IQR(data$SalePrice)
print(lf)
uf<-quantile(data$SalePrice)+1.5*IQR(data$SalePrice)
print(uf)
outer_values<-boxplot.stats(data$SalePrice)$out
print(outer_values)

diabetes1<-table(data$Id,data$SalePrice)
print(diabetes1)
 chi sq.test(diabetes1)


names = c("sathish","kumar","Abdul")
age = c(19,18,20)
marks = c(25,26,27)
df<-data.frame(names,age,marks)
View(df)
write.csv(df,"abc.csv")
